# using standard lib csv module to read and write csv files
# The csv module implements classes to read and write tabular data in CSV format.
# It allows programmers to say, “write this data in the format preferred by Excel,”
# or “read data from this file which was generated by Excel,” without knowing the precise details of the CSV format used by Excel.
# Programmers can also describe the CSV formats understood by other applications or define their own special-purpose CSV formats.
# The csv module’s reader and writer objects read and write sequences.
# Programmers can also read and write data in dictionary form using the DictReader and DictWriter classes.

import csv

with open('testdata.csv', 'r', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    print(reader)
    for row in reader:
        #print(', '.join(row))
        print(row[4])
